### ISSUE TITLE
How can we change contents?

### ISSUE THREAD

**Issue by gelavat** [unicate/pico-bulma#2]
Hello.

How can we change the contents of the theme, once installed properly?

For example, I would like to do those things but I don't know how:
- Edit the "Welcome" and "Details" links at the top
- Change or remove the "Github" and "Packagist" links at the top of the first page
- Edit the "Repositories", "John Smith" and "Password" sections
- Changing the background blue to white at the top or modifying the colors
- Changing the full background color or even put an image behind it all

A user manual would be great.
Thank you

**Comment by unicate** [comment]
Hi

The Navigation is built from the Pico Meta-Tags inside your content pages. (please refer to the Pico docs)

```
---
Title: Welcome
Description: This description will go in the meta description tag
Author: Joe Bloggs
Date: 2001-04-25
Robots: noindex,nofollow
Template: index
---
```

Github links, Repositories, etc. are just examples and can be edited directely in the index.twig file.

To change colors you need to build the project using Gulp and create a new theme. 
Color etc. can be changed with the variables.scss and styles.scss in the SASS folder.

Hope it helps.

**Comment by gelavat** [comment]
Thank you very much for your answer, yes it helps.
I managed to modify the theme and pages to do all changes needed.

For the colors in variables.css and style.css I think you are refering to the '/theme/bulma/css' directory as sass directory doesn't exist.

I will provide another ticket for a request of doc update.
